# bashrc file
export WORKON_HOME=/Users/ytu/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export WORKON_HOME=$HOME/.virtualenvs
export PATH="/usr/local/share/python:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
alias l="ls -al"
alias fb="git status " # fenerbahce !
alias ga="git add "
alias gb="git branch "
alias gc="git commit "
alias gp="git push -u origin "
alias gd="git diff"
alias go="git checkout "
alias gk="gitk --all&"
alias gx="gitx --all"
alias plus="python manage.py shell_plus" # Django-extension
